// Order codes: six characters from an alphabet without 0/O/1/I, generated by
// the database. These helpers only tidy what a human or a camera produced.

const CODE_RE = /^[A-Z0-9]{4,8}$/;

// Upper-case, trimmed, or null when it can't be a code.
export function normaliseOrderCode(value: string): string | null {
  const code = value.trim().toUpperCase();
  return CODE_RE.test(code) ? code : null;
}

// Pull a code out of whatever the camera saw: our own scan URL
// (…/waiter/scan?code=K7M2QD), a bare code, or nothing.
export function codeFromScan(text: string): string | null {
  const trimmed = text.trim();
  try {
    const url = new URL(trimmed);
    const param = url.searchParams.get("code");
    return param ? normaliseOrderCode(param) : null;
  } catch {
    return normaliseOrderCode(trimmed);
  }
}
