import Link from "next/link";
import { Download, ExternalLink, Star } from "lucide-react";

import { CopyUrl } from "@/components/dashboard/CopyUrl";

// A second, smaller QR alongside the menu one. It points at /r/<slug> so a
// restaurant can print it on the bill or a table card and collect feedback
// without sending guests through the menu first.
//
// Rendered server-side using the existing /api/qr endpoint rather than the
// canvas-based QrStudio: this code never changes once printed, so there's
// nothing to interact with.
export function ReviewQrCard({
  reviewUrl,
  restaurantName,
  isEnabled,
  isPublished,
}: {
  reviewUrl: string;
  restaurantName: string;
  isEnabled: boolean;
  isPublished: boolean;
}) {
  const qrSrc = `/api/qr?url=${encodeURIComponent(reviewUrl)}&size=512`;
  const live = isEnabled && isPublished;

  return (
    <section className="mt-10 rounded-2xl border border-neutral-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900">
      <div className="flex items-center gap-2 text-brand-600">
        <Star className="h-4 w-4" />
        <h2 className="text-xs font-semibold uppercase tracking-wide">
          Review QR code
        </h2>
      </div>

      <p className="mt-2 max-w-xl text-sm text-neutral-500">
        Print this one on the bill or a table card. Scanning it opens your
        review form — submissions wait in{" "}
        <Link
          href="/dashboard/reviews"
          className="font-medium text-brand-600 hover:underline"
        >
          Reviews
        </Link>{" "}
        until you approve them.
      </p>

      <div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-start">
        <div className="shrink-0 rounded-xl border border-neutral-200 bg-white p-3 dark:border-neutral-700">
          {/* Plain <img>: the QR is generated by our own route handler and is
              already exactly the size we draw it at, so next/image would add
              an optimizer hop for nothing. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={qrSrc}
            alt={`QR code linking to the review page for ${restaurantName}`}
            width={176}
            height={176}
            className="h-44 w-44"
          />
        </div>

        <div className="min-w-0 flex-1 space-y-3">
          <CopyUrl url={reviewUrl} />

          <div className="flex flex-wrap gap-2">
            <a
              href={`${qrSrc}&size=1024`}
              download={`${restaurantName} review QR.png`}
              className="inline-flex items-center gap-1.5 rounded-lg border border-neutral-200 px-3 py-1.5 text-xs font-medium text-neutral-600 transition-colors hover:bg-neutral-100 dark:border-neutral-700 dark:text-neutral-300 dark:hover:bg-neutral-800"
            >
              <Download className="h-3.5 w-3.5" /> Download PNG
            </a>
            <a
              href={reviewUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1.5 rounded-lg border border-neutral-200 px-3 py-1.5 text-xs font-medium text-neutral-600 transition-colors hover:bg-neutral-100 dark:border-neutral-700 dark:text-neutral-300 dark:hover:bg-neutral-800"
            >
              <ExternalLink className="h-3.5 w-3.5" /> Open
            </a>
            <Link
              href="/dashboard/reviews/settings"
              className="inline-flex items-center gap-1.5 rounded-lg border border-neutral-200 px-3 py-1.5 text-xs font-medium text-neutral-600 transition-colors hover:bg-neutral-100 dark:border-neutral-700 dark:text-neutral-300 dark:hover:bg-neutral-800"
            >
              Edit the form
            </Link>
          </div>

          {!live ? (
            <p className="rounded-md bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:bg-amber-950/40 dark:text-amber-300">
              {!isPublished
                ? "Your menu isn't published yet, so this code won't resolve for guests."
                : "The review page is switched off in Review Settings, so this code won't resolve for guests."}
            </p>
          ) : null}
        </div>
      </div>
    </section>
  );
}
